services:
  - type: web
    name: multi-vendor-food-ordering-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
